### ISSUE TITLE
Check header files for bad practices

### ISSUE THREAD

**Issue by daniel-v-k** [rreinecke/global-gradient-based-groundwater-model#25]
Found on microsoft.com:
"Because a header file might potentially be included by multiple files, it cannot contain definitions that might produce multiple definitions of the same name. The following are not allowed, or are considered very bad practice:
-     built-in type definitions at namespace or global scope
-     non-inline function definitions
-     non-const variable definitions
-     aggregate definitions
-     unnamed namespaces
-     using directives

Use of the using directive will not necessarily cause an error, but can potentially cause a problem because it brings the namespace into scope in every .cpp file that directly or indirectly includes that header."
